config/routes.rb
Rails.application.routes.draw do
  resources :vids
 #root :to => 'stati#index'

  resources :pics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord

   mount_base64_uploader :photo, PhotoUploader
   
   
end

app/models/vid.rb
class Vid < ApplicationRecord
  mount_uploader :file, VideoUploader
  
  def set_success(format, opts)
    self.success = true
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show]

  # GET /pics
  def index
    @pics = Pic.all.limit(20).reverse

    render json: @pics
  end

  # GET /pics/1
  def show
    render json: @pic
  end

  # POST /pics
  def create
    @pic = Pic.new(pic_params)

    if @pic.save
      render json: @pic, status: :created, location: @pic
    else
      render json: @pic.errors, status: :unprocessable_entity
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pic_params
      params.require(:pic).permit(:photo, :string)
    end
end

app/controllers/stati_controller.rb
class StatiController < ApplicationController
  def index
  end
end

app/controllers/vids_controller.rb
class VidsController < ApplicationController
  before_action :set_vid, only: [:show, :edit, :update, :destroy]

  # GET /vids
  def index
    @vids = Vid.all
  end

  # GET /vids/1
  def show
  end

  # GET /vids/new
  def new
    @vid = Vid.new
  end

  # GET /vids/1/edit
  def edit
  end

  # POST /vids
  def create
    @vid = Vid.new(vid_params)

    if @vid.save
      redirect_to @vid, notice: 'Vid was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /vids/1
  def update
    if @vid.update(vid_params)
      redirect_to @vid, notice: 'Vid was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /vids/1
  def destroy
    @vid.destroy
    redirect_to vids_url, notice: 'Vid was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vid
      @vid = Vid.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def vid_params
      params.require(:vid).permit(:video, :string)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vids_helper.rb
module VidsHelper
end

app/views/stati/index.html.erb
<h1>Home#home</h1>
<p>Find me in app/views/home/home.html.erb</p>

app/views/vids/_form.html.erb
<%= form_for(vid) do |f| %>
  <% if vid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vid.errors.count, "error") %> prohibited this vid from being saved:</h2>

      <ul>
      <% vid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video %>
    <%= f.text_field :video %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vids/edit.html.erb
<h1>Editing Vid</h1>

<%= render 'form', vid: @vid %>

<%= link_to 'Show', @vid %> |
<%= link_to 'Back', vids_path %>

app/views/vids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vids</h1>

<table>
  <thead>
    <tr>
      <th>Video</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vids.each do |vid| %>
      <tr>
        <td><%= vid.video %></td>
        <td><%= vid.string %></td>
        <td><%= link_to 'Show', vid %></td>
        <td><%= link_to 'Edit', edit_vid_path(vid) %></td>
        <td><%= link_to 'Destroy', vid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vid', new_vid_path %>

app/views/vids/new.html.erb
<h1>New Vid</h1>

<%= render 'form', vid: @vid %>

<%= link_to 'Back', vids_path %>

app/views/vids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Video:</strong>
  <%= @vid.video %>
</p>

<p>
  <strong>String:</strong>
  <%= @vid.string %>
</p>

<%= link_to 'Edit', edit_vid_path(@vid) %> |
<%= link_to 'Back', vids_path %>